export const ADD_ITEM = "ADD_ITEM";
export const MOVE_CHILD_TO_CONTAINER = "MOVE_CHILD_TO_CONTAINER";
export const ADD_ELEMENT_AS_CHILD = "ADD_ELEMENT_AS_CHILD";

export const SET_FORM_M0DAL_VISIBILITY = "SET_FORM_M0DAL_VISIBILITY";
export const UPDATE_ELEMENT_PROPERTIES = "UPDATE_ELEMENT_PROPERTIES";

export const SET_SELECTED_ELEMENT_ID = "SET_SELECTED_ELEMENT_ID";
export const DELETE_SELECTED_ELEMENT = "DELETE_SELECTED_ELEMENT";

export const SET_SIDEBAR_WIDTH = "SET_SIDEBAR_WIDTH";
export const SET_INITIAL_COODS = "SET_INITIAL_COODS";

export const SET_STATE_FROM_LOCAL_STORAGE = "SET_STATE_FROM_LOCAL_STORAGE";
export const RESET_ALL_DATA = "RESET_ALL_DATA";
